### ISSUE TITLE
Trying to make a Bit-error-rate tester in Python

### ISSUE THREAD

**Issue by AB-Normal1960** [dalegambill/PythonTerminal#1]
Hello Dale.
I love your code. I am just learning PY. I work testing very long serial cables either RS-232 or RS-432 or RS-485. I have an old laptop with Windows XP and a hardware serial port. I use it to test cable.

So, My plan is to put short the send and receive together at the distant end of the cable.
I put my laptop with the PY BERT software on the other end of the cable.

I have started a program in Python that 1st asks for the com port#, then the baud rate. I leave the defaults for the Pyserial as 8 bits, no parity and 1 stop bit.

So, then the program asks how many characters to send.  I usually test at 9600 baud, so I enter 20,000 characters.

I then start a for loop and say that i=range (numcharacters)
and then I build a very long string
SendSTR=("")
I put that above the input line to declare it but make it empty.
Then I do a loop that creates a random ASCII number and appends it to the SendStr variable.
That loop repaeats the numcharacters # of times so we now have a very long string.

Then, on character at a time(again, I am thinking a loop) that sends one caracter from the generated string down the serial line, then receives it back( the distant end is in a loopback on the wires) then I compare what was sent with what was recieved. If the two are equal, sent chars counter increments by 1, but error counter remains zero. If the recieved character was NOT what was sent, then the sent character increments by 1 but the Error counter also increments by one.

This is repeated until the entire 20,000 character string is sent.

Then the loops are done and a report is printed:

Print (charsend+ " characters sent.")
Print (errors+ "Recieved")

Then I do some math to come up with a percentage of the errors to sent successfully.

Of course, I am new at this and this is not the best code, but it is good enough.
What do you think?

Maybe you can make something like this quicker than me, I suppose.
I am not sure if I am on the correct tab in Github to just chat about a thing.
I enjoy your code. It inspires me to continue, but I must look into the Class and the Def things.
Thank you for posting this.

**Comment by dalegambill** [comment]
Hello,
You could use serial_rx_tx.py as posted here, but it is line-oriented (sends and receives lines terminated by \n).  You could create and send a string or series of strings as long as desired and each terminated with a \n.  You should wait a few ms between sending each line to ensure that the COM port send buffer does not overflow.
-Dale-

**Comment by dalegambill** [comment]
Not an issue.
